version: "3.9"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-js:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PGUSER=myuser
      - PGPASSWORD=mypassword
      - PGDATABASE=mydatabase
      - PGHOST=database    # 👈 must match the service name
      - PGPORT=5432
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules     # mount only backend code into /app
    restart: unless-stopped
    develop:
      watch:
        - path: backend/package.json
          action: rebuild
        - path: backend/Dockerfile
          action: rebuild
        - path: backend/server.js
          action: rebuild

volumes:
  postgres_data:
